In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import datetime
import numpy as np

In [2]:
glasses = pd.read_csv('data/glasses.csv')
glasses['DATE'] = pd.to_datetime(glasses['DATE'])
glasses = glasses.set_index('DATE')
glasses = glasses.sort_values('DATE')

glasses_grouped = glasses.groupby(pd.TimeGrouper(freq='Min')).agg({
    'ACC_X': 'mean',
    'ACC_Y': 'mean',
    'ACC_Z': 'mean',
    'GYRO_X': 'mean',
    'GYRO_Y': 'mean',
    'GYRO_Z': 'mean',
    'EOG_L': 'mean',
    'EOG_R': 'mean',
    'EOG_H': 'mean',
    'EOG_V': 'mean',
})
glasses_grouped['eog'] = np.sqrt(
    glasses_grouped['EOG_H'] ** 2 + 
    glasses_grouped['EOG_L'] ** 2 + 
    glasses_grouped['EOG_R'] ** 2 + 
    glasses_grouped['EOG_V'] ** 2
)
# eog = glasses_grouped[['eog']]
eog = glasses_grouped[['EOG_V']]

/home/hossein/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: pd.TimeGrouper is deprecated and will be removed; Please use pd.Grouper(freq=...)

In [3]:
smartwatch = pd.read_csv('data/smartwatch.csv')
heart_rate = smartwatch[smartwatch['source']=='heart_rate']
heart_rate['timestamp'] = pd.to_datetime(heart_rate['timestamp'])
heart_rate = heart_rate.sort_values('timestamp')
heart_rate = heart_rate.set_index('timestamp')

heart_rate['heart_rate'] = heart_rate['values'].map(lambda hr: float(hr.split('\'')[1]))
heart_rate = heart_rate.groupby(pd.TimeGrouper(freq='Min')).agg({
    'heart_rate': 'mean',
})

/home/hossein/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/hossein/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: FutureWarning: pd.TimeGrouper is deprecated and will be removed; Please use pd.Grouper(freq=...)

In [4]:
smartwatch_acceleration = smartwatch[smartwatch['source']=='linear_acceleration']

smartwatch_acceleration['timestamp'] = pd.to_datetime(smartwatch_acceleration['timestamp'])
smartwatch_acceleration = smartwatch_acceleration.sort_values('timestamp')
smartwatch_acceleration = smartwatch_acceleration.set_index('timestamp')

smartwatch_acceleration['smartwatch_acceleration'] = smartwatch_acceleration['values'].map(
    lambda hr: np.sqrt(
        float(hr.split('\'')[1]) ** 2 + 
        float(hr.split('\'')[3]) ** 2 + 
        float(hr.split('\'')[5]) ** 2
    )
)
smartwatch_acceleration = smartwatch_acceleration.groupby(pd.TimeGrouper(freq='Min')).agg({
    'smartwatch_acceleration': 'mean',
})

/home/hossein/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/hossein/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: FutureWarning: pd.TimeGrouper is deprecated and will be removed; Please use pd.Grouper(freq=...)

In [5]:
smartphone = pd.read_csv('data/smartphone.csv')
pressure = smartphone[smartphone['source']=='pressure']
pressure['timestamp'] = pd.to_datetime(pressure['timestamp'])
pressure = pressure.sort_values('timestamp')
pressure = pressure.set_index('timestamp')

pressure['pressure'] = pressure['values'].map(lambda hr: float(hr.split('\'')[1]))
pressure = pressure.groupby(pd.TimeGrouper(freq='Min')).agg({
    'pressure': 'mean',
})

/home/hossein/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/hossein/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: FutureWarning: pd.TimeGrouper is deprecated and will be removed; Please use pd.Grouper(freq=...)

In [6]:
smartphone_acceleration = smartphone[smartphone['source']=='linear_acceleration']

smartphone_acceleration['timestamp'] = pd.to_datetime(smartphone_acceleration['timestamp'])
smartphone_acceleration = smartphone_acceleration.sort_values('timestamp')
smartphone_acceleration = smartphone_acceleration.set_index('timestamp')

smartphone_acceleration['smartphone_acceleration'] = smartphone_acceleration['values'].map(
    lambda hr: np.sqrt(
        float(hr.split('\'')[1]) ** 2 + 
        float(hr.split('\'')[3]) ** 2 + 
        float(hr.split('\'')[5]) ** 2
    )
)
smartphone_acceleration = smartphone_acceleration.groupby(pd.TimeGrouper(freq='Min')).agg({
    'smartphone_acceleration': 'mean',
})

/home/hossein/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/hossein/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: FutureWarning: pd.TimeGrouper is deprecated and will be removed; Please use pd.Grouper(freq=...)

In [8]:
report = pd.read_csv('data/report.csv')
labels = pd.DataFrame(columns=['timestamp', 'activity'])
for i, r in report.iterrows():
    min_diff = int(
        (
            datetime.datetime.strptime(r['to'], '%m/%d/%Y %H:%M') - 
             datetime.datetime.strptime(r['from'], '%m/%d/%Y %H:%M')
        ).total_seconds() / 60
    )
    for i in range(min_diff):
        labels = labels.append(pd.DataFrame(
            [{
                'timestamp': datetime.datetime.strptime(r['from'], '%m/%d/%Y %H:%M') + datetime.timedelta(minutes=i),
                'activity': r['activity_type']
            }]
        ), ignore_index=True)
labels = labels.set_index('timestamp')

/home/hossein/.local/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [9]:
agg = (eog
        .join(pressure)
        .join(heart_rate)
        .join(smartphone_acceleration)
        .join(smartwatch_acceleration)
        .join(labels)
      )
agg

,EOG_V,pressure,heart_rate,smartphone_acceleration,smartwatch_acceleration,activity
2017-06-29 08:00:00,81.703020,968.106713,64.857143,0.219879,0.034714,NaN
2017-06-29 08:01:00,86.097000,968.080578,62.000000,0.206890,NaN,NaN
2017-06-29 08:02:00,83.987667,968.078702,54.217391,0.052642,0.071597,NaN
2017-06-29 08:03:00,83.122333,968.080108,60.000000,0.054307,NaN,NaN
2017-06-29 08:04:00,79.543667,968.072910,NaN,0.075880,NaN,NaN
2017-06-29 08:05:00,85.204667,968.069837,NaN,0.091469,NaN,NaN
2017-06-29 08:06:00,75.201333,968.096890,NaN,0.071118,NaN,NaN
2017-06-29 08:07:00,76.697667,968.114769,NaN,0.072312,NaN,NaN
2017-06-29 08:08:00,73.448000,968.116464,55.965517,0.033457,0.116044,NaN
2017-06-29 08:09:00,77.180333,968.107668,67.880000,0.792770,0.213772,NaN
2017-06-29 08:10:00,80.829333,968.082286,66.909091,1.037830,0.452178,NaN
2017-06-29 08:11:00,75.993000,968.076574,64.285714,0.382107,0.329883,NaN
2017-06-29 08:12:00,79.344333,968.085637,57.615385,0.277960,0.213739,NaN
2017-06-29 08:13:00,74.122333,968.064355,NaN,0.210619,0.068185,NaN
2017-06-29 08:14:00,74.269333,968.078638,54.833333,0.080331,NaN,NaN
2017-06-29 08:15:00,72.373333,968.073488,61.714286,0.062431,0.043677,NaN
2017-06-29 08:16:00,77.158667,968.088224,63.888889,0.039377,2.074522,NaN
2017-06-29 08:17:00,81.227333,968.064048,62.900000,3.017585,1.038829,NaN
2017-06-29 08:18:00,69.996106,968.040434,60.625000,1.658024,1.069781,NaN
2017-06-29 08:19:00,87.944783,968.022165,63.600000,0.529011,2.097871,NaN
2017-06-29 08:20:00,58.641892,968.015798,70.000000,0.873688,0.778364,NaN
2017-06-29 08:21:00,NaN,968.029209,64.000000,1.290938,0.370917,NaN
2017-06-29 08:22:00,NaN,968.030635,64.555556,1.270010,0.650479,NaN
2017-06-29 08:23:00,NaN,967.992558,69.000000,1.667064,4.081109,NaN
2017-06-29 08:24:00,NaN,967.998634,68.222222,1.617424,1.608153,NaN
2017-06-29 08:25:00,NaN,967.975088,73.294118,3.405913,2.084428,NaN
2017-06-29 08:26:00,NaN,967.980110,76.333333,1.458573,2.134243,NaN
2017-06-29 08:27:00,NaN,967.997941,68.625000,1.095849,2.581353,NaN
2017-06-29 08:28:00,NaN,967.993750,66.125000,0.637932,0.260977,NaN
2017-06-29 08:29:00,NaN,967.997602,69.888889,1.392761,1.647906,NaN
...,...,...,...,...,...,...
2017-07-13 21:51:00,80.602333,NaN,NaN,NaN,NaN,NaN
2017-07-13 21:52:00,75.883667,NaN,NaN,NaN,NaN,NaN
2017-07-13 21:53:00,67.020000,NaN,NaN,NaN,NaN,NaN
2017-07-13 21:54:00,79.466667,NaN,NaN,NaN,NaN,NaN
2017-07-13 21:55:00,80.511333,NaN,NaN,NaN,NaN,NaN
2017-07-13 21:56:00,78.681000,NaN,NaN,NaN,NaN,NaN
2017-07-13 21:57:00,77.914000,NaN,NaN,NaN,NaN,NaN
2017-07-13 21:58:00,76.574667,NaN,NaN,NaN,NaN,NaN
2017-07-13 21:59:00,77.709333,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:00:00,74.336000,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:01:00,77.446000,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:02:00,77.060000,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:03:00,86.101000,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:04:00,75.638333,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:05:00,76.363000,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:06:00,77.175667,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:07:00,78.200333,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:08:00,76.142000,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:09:00,77.172333,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:10:00,76.065000,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:11:00,77.021000,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:12:00,75.678667,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:13:00,61.639333,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:14:00,75.591667,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:15:00,77.293000,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:16:00,74.499667,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:17:00,71.137667,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:18:00,75.794000,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:19:00,77.119667,NaN,NaN,NaN,NaN,NaN
2017-07-13 22:20:00,73.369270,NaN,NaN,NaN,NaN,NaN

In [11]:
agg.to_csv('data/agg.csv', index_label='timestamp')

In [14]:
agg.corr()

,EOG_V,pressure,heart_rate,smartphone_acceleration,smartwatch_acceleration
EOG_V,1.000000,-0.113591,-0.118595,-0.012612,0.018757
pressure,-0.113591,1.000000,0.002225,-0.032622,-0.039457
heart_rate,-0.118595,0.002225,1.000000,0.699081,0.543644
smartphone_acceleration,-0.012612,-0.032622,0.699081,1.000000,0.697532
smartwatch_acceleration,0.018757,-0.039457,0.543644,0.697532,1.000000

In [15]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler